### ISSUE TITLE
incompatible with python 3 syntax

### ISSUE THREAD

**Issue by kevhill** [GoogleCloudPlatform/gcs-oauth2-boto-plugin#30]
version 1.14

```
>>> import gcs_oauth2_boto_plugin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/gcs_oauth2_boto_plugin/__init__.py", line 26, in <module>
    from gcs_oauth2_boto_plugin import oauth2_plugin
  File "/usr/local/lib/python3.6/site-packages/gcs_oauth2_boto_plugin/oauth2_plugin.py", line 22, in <module>
    from gcs_oauth2_boto_plugin import oauth2_client
  File "/usr/local/lib/python3.6/site-packages/gcs_oauth2_boto_plugin/oauth2_client.py", line 125
    except KeyError, e:
                   ^
SyntaxError: invalid syntax
```

**Comment by bharris47** [comment]
Experiencing same issue on CPython 3.5 on OS X Yosemite 10.10.5.

**Comment by EmlynC** [comment]
Same issue as #29, pull request #34 should address these issues.

**Comment by houglum** [comment]
Major version 2 introduced Py3 compatibility; closing this.
